# Generated by Django 5.1.5 on 2025-05-17 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wiki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wiki_pages',
            name='description_path',
        ),
        migrations.CreateModel(
            name='Craft_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('station', models.CharField(max_length=30)),
                ('url_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_wiki.wiki_pages')),
            ],
        ),
    ]
