# Generated by Django 5.1.5 on 2025-05-17 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wiki', '0002_remove_wiki_pages_description_path_craft_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('item_image_path', models.CharField(max_length=100)),
                ('placed_or_not', models.CharField(max_length=3)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='craft_card',
            name='url_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_wiki.wiki_page'),
        ),
        migrations.DeleteModel(
            name='Wiki_pages',
        ),
    ]
