# Generated by Django 5.1.5 on 2025-05-24 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wiki', '0003_wiki_page_alter_craft_card_url_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='craft_card',
            name='url_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_wiki.article'),
        ),
        migrations.AlterField(
            model_name='wiki_page',
            name='url_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_wiki.article'),
        ),
    ]
