# Generated by Django 5.1.5 on 2025-05-24 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wiki', '0004_article_alter_craft_card_url_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craft_card',
            name='url_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_wiki.wiki_page'),
        ),
        migrations.AlterField(
            model_name='wiki_page',
            name='url_title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
