# Generated by Django 5.1.5 on 2025-05-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wiki', '0005_alter_craft_card_url_title_alter_wiki_page_url_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craft_card',
            name='url_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craft_cards', to='main_wiki.wiki_page'),
        ),
    ]
