# Generated by Django 5.1.5 on 2025-05-24 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wiki', '0006_alter_craft_card_url_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craft_card',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='craft_card',
            name='ingredients_item_image_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='craft_card',
            name='ingredients_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
