# Generated by Django 5.1.5 on 2025-05-31 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wiki', '0007_remove_craft_card_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft_card',
            name='station_image_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
