# Generated by Django 5.1.5 on 2025-05-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wiki', '0009_alter_craft_card_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craft_card',
            name='amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='craft_card',
            name='ingredients_item_image_path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='craft_card',
            name='station',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='craft_card',
            name='station_image_path',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='wiki_page',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
