# Generated by Django 5.1.5 on 2025-05-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wiki', '0010_alter_craft_card_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craft_card',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
